### PR TITLE
Structuring git command lines section

### PR DESCRIPTION
**Pull request by DelazJ**
Hi Matteo
Based on your work and the discussion we have in your PR thread, I took the liberty to propose you enhancements I was talking about in scenario c' and d'. You have a better overview of the proposal at https://github.com/DelazJ/QGIS-Documentation/blob/a43e5ae0cd6ee47463151bbc7ddb0da03f025ed0/source/docs/documentation_guidelines/first_contribution.rst
As you'd see, the idea is to have one description of the process and just point the part it diverges, according to branches matters.
I also took the opportunity to fix some texts.
Note that I'm working on an improvement of this chapter to better explain/complete process. Available at https://github.com/DelazJ/QGIS-Documentation/blob/guidelines/source/docs/documentation_guidelines/first_contribution.rst (not yet finished and some conflicts with current branch. 
Let me know what you think about this structure of the chapter and feel free to merge it or no in your branch.

### CODE REVIEW

**Comment by ghtmtt** [comment]
Hey, I love that chapter, really. Easy to understand and very straightforward.
One thing we can add, is what you can do if you push some commits but you forget to update you repository first. 
And maybe super brief explain what conflicts are and provide a link to a git website on how to fix them.
Thoughts? 
BTW: thanks for all your efforts!

**Comment by DelazJ** [comment]
> One thing we can add, is what you can do if you push some commits but you forget to update you repository first.
And maybe super brief explain what conflicts are and provide a link to a git website on how to fix them.

These are somehow parts of the FAQ we were talking about last day. It could come at the end of the chapter and we could spread internal link in the current description. I already opened an issue report so that we recall it.
But given the length of the discussion in your initial PR, I think it's good to fix it in another PR. It will also need comments from others (and not sure there are currently many people that follow our discussion and who can contribute). A new PR will be a new beginning.

So, if you are ok with this proposal, merge it and let's see what Travis says :)

**Comment by ghtmtt** [comment]
Ok I'll merge it and get rid of my old PR. So we don't mix branches and we can start clean ;)

**Comment by DelazJ** [comment]
No problem to mix. Just merge it and it will be added to your PR

**Pull request merged**
